### ISSUE TITLE
Can anyone help me?

### ISSUE THREAD

**Issue by ghost** [mouseless-eth/rusty-sando#16]
I'm getting these errors when I cargo test and cargo run

[16:51:18][INFO] all_pools_len: 0
 [16:51:18][INFO] Found 0 tokens worth of dust
thread 'main' panicked at 'called Result::unwrap() on an Err value: Invalid name: please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning 0x in case contract or method don't exist

Anyone know why? Maybe my erigon node isn't setup properly, I run it with --ws 
The node is running.

![Error 2](https://github.com/mouseless-eth/rusty-sando/assets/136131557/18ce3e10-0082-4917-b882-4d277af4c7ce)
![Error](https://github.com/mouseless-eth/rusty-sando/assets/136131557/f0e7f92a-cba3-4956-bcb4-531154eb5b61)

**Comment by xbhuang1994** [comment]
You need to deploy the contract

**Comment by ghost** [comment]
can you give me a indepth guide on how to deploy contract please? thank you.
