### ISSUE TITLE
Recover funds

### ISSUE THREAD

**Issue by 0xsepu** [mouseless-eth/rusty-sando#19]
Hello, was wondering how can I recover funds I sent to the contract ?

**Comment by thedivine1** [comment]
> Hello, was wondering how can I recover funds I sent to the contract ?

Did you make a profit bud? Can this run as is on BSC?

**Comment by SadeRespector** [comment]
Look in closed issues, this has been addressed

**Comment by 0xsepu** [comment]
> > Hello, was wondering how can I recover funds I sent to the contract ?
> 
> Did you make a profit bud? Can this run as is on BSC?

Unfortunately no, I keep getting Nonce too low and I can't figure out why.
As for BSC you should be able to but I don't think its worth.
