### ISSUE TITLE
metamorphic contracts

### ISSUE THREAD

**Issue by PraveenAlexis** [mouseless-eth/rusty-sando#38]
Hi,

Sorry for this but can someone explain how can i get this done? im asking because there is a lack of documentation in this 

"Fill in the searcher address in Huff contract and deploy either straight onchain or via create2 using a [metamorphic](https://github.com/0age/metamorphic) like factory."

**Comment by greekfetacheese** [comment]
You can use Keyless Create2 Factory to deploy the huff contract.

Install huff compiler `curl -L get.huff.sh | bash`

Get the contracts bytecode with `huffc src/sando.huff --bytecode`

Copy the contracts bytecode and use it to uploaded with the SafeCreate2 method, you can use this nodejs script https://github.com/Cionn3/create2-factory-contract-deploy

Make sure you run the huff compiler from the contracts folder

**Comment by PraveenAlexis** [comment]
is this an alternative method to using metamorphic factory?

**Comment by greekfetacheese** [comment]
i think basically its the same thing, you can also find more info here: https://github.com/0age/metamorphic
