### ISSUE TITLE
Sandwish Contract and Inception Block

### ISSUE THREAD

**Issue by imcodingideas** [mouseless-eth/rusty-sando#39]
Hello,

I'm exploring the documentation at [this location](https://github.com/mouseless-eth/rusty-sando/tree/master/bot#usage), specifically focusing on the environment variables under the "Usage" section. There are two values that I need clarification on:

```
SANDWICH_CONTRACT=0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa
SANDWICH_INCEPTION_BLOCK=...
```

I need to create and fund a smart contract? Whats an Inception Block? I have some hints [here](https://github.com/mouseless-eth/rusty-sando/issues/38#issuecomment-1663362224), thanks @Cionn3 

1. I'm looking for guidance on how to generate the `FLASHBOTS_AUTH_KEY`. Could you provide some information or direct me to resources that explains how to obtain this key?
2. Finally, I have a question about the Erigon archive node. I began the sync process around two days ago. Is it necessary for me to wait for it to completely synchronize and index before continuing? 

![Screenshot 2023-08-04 at 6 52 15 PM](https://github.com/mouseless-eth/rusty-sando/assets/5374985/c42e2af9-10fd-4606-8cff-ac21ed85ec90)

Thank you for your experience, and I look forward to your reply. Cheers.

**Comment by popfendi** [comment]
Yes you have to deploy the sandwich contract, INCEPTION_BLOCK is the block number that your contract deployment transaction was in. 

The flashbots Auth key is just a private key, doesn't need to be funded, it's just so flashbots can authorize you. 

Regarding your erigon node, I'd assume you aren't running a consensus client? If so, check out lighthouse.

**Comment by imcodingideas** [comment]
thank you @popfendi I added theses suggestions to the README https://github.com/mouseless-eth/rusty-sando/pull/43
