### ISSUE TITLE
huff WETH

### ISSUE THREAD

**Issue by imcodingideas** [mouseless-eth/rusty-sando#44]
Hello,

I would like to ask for some guidance on which Constants should I care about when I am creating the contract?

https://github.com/mouseless-eth/rusty-sando/blob/master/contract/src/sando.huff#L17C67-L17C67 

I understand that the SEARCHER is the same key from SEARCHER_PRIVATE_KEY https://github.com/mouseless-eth/rusty-sando/blob/master/bot/.env.example#L2

What about the WETH? Is this the WETH address that Im using in the smart contract?

**Comment by PraveenAlexis** [comment]
@imcodingideas sorry im not helpful here, however i have a few questions regarding SEARCHER_PRIVATE_KEY and FLASHBOTS_AUTH_KEY.

is FLASHBOTS_AUTH_KEY a wallet address?
is SEARCHER_PRIVATE_KEY the private key of that wallet?

**Comment by imcodingideas** [comment]
I had the same questions. An awesome person on this repo helped me privately, and another publicly here https://github.com/mouseless-eth/rusty-sando/issues/39#issuecomment-1666423362  

I tried to add this info into the README but @mouseless-eth didn't want to recreate the internet which is fair. We all start somewhere. 

### What is the FLASHBOTS_AUTH_KEY?

The `FLASHBOTS_AUTH_KEY` is utilized as a method to track your representation with Flashbots. If you are setting up for the first time, refer to [MetaMask's guide on creating an additional account](https://support.metamask.io/hc/en-us/articles/360015289452-How-to-create-an-additional-account-in-your-wallet) in your wallet. The `FLASHBOTS_AUTH_KEY` is any private key. It's recommended to generate a new one from MetaMask or a similar service, and use an unfunded one. This key is used to establish your reputation on Flashbots.

### What is the SEARCHER_PRIVATE_KEY?

The `SEARCHER_PRIVATE_KEY` corresponds to your private key. This key should be updated in your environment variables. It's this key that will be responsible for paying fees and utilizing the contract. Remember to update it [here](https://github.com/mouseless-eth/rusty-sando/blob/master/contract/src/sando.huff#L18).
