### ISSUE TITLE
Cannot deploy the contract

### ISSUE THREAD

**Issue by gusy383891** [mouseless-eth/rusty-sando#46]
Hi,

Same problem deploying the contract as here #20 and here #33 and fix 3fb7081 did not resolve the issue.

`"You have an active prank. Broadcasting and pranks are not compatible. Disable one or the other"`

`[2166321] → new Deployer@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    └─ ← 10599 bytes of code
  [98] Deployer::setUp() 
    └─ ← ()
  [2113497] Deployer::run() 
    ├─ [1981204] → new HuffConfig@0xC7f2Cf4845C6db0e1a1e91ED41Bcd0FcC1b0E141
    │   └─ ← 9785 bytes of code
    ├─ [679] HuffConfig::set_broadcast(true) 
    │   └─ ← HuffConfig: [0xC7f2Cf4845C6db0e1a1e91ED41Bcd0FcC1b0E141]
    ├─ [74581] HuffConfig::deploy(sando) 
    │   ├─ [0] VM::ffi([./lib/foundry-huff/scripts/binary_check.sh]) 
    │   │   └─ ← 0x01
    │   ├─ [0] VM::ffi([./lib/foundry-huff/scripts/rand_bytes.sh]) 
    │   │   └─ ← 0x0e733023c11bfe6a8965c755c2d8500a
    │   ├─ [0] VM::ffi([./lib/foundry-huff/scripts/file_writer.sh, src/__TEMP__bpwamwyejjqqmzlxebcshznkhdjwbethsando.huff, 
]) 
   │   ├─ [0] VM::prank(HuffConfig: [0xC7f2Cf4845C6db0e1a1e91ED41Bcd0FcC1b0E141]) 
    │   │   └─ ← ()
    │   ├─ [0] VM::ffi([rm, src/__TEMP__bpwamwyejjqqmzlxebcshznkhdjwbethsando.huff]) 
    │   │   └─ ← 0x
    │   ├─ [0] VM::broadcast() 
    │   │   └─ ← "You have an active prank. Broadcasting and pranks are not compatible. Disable one or the other"
    │   └─ ← "You have an active prank. Broadcasting and pranks are not compatible. Disable one or the other"
    └─ ← "You have an active prank. Broadcasting and pranks are not compatible. Disable one or the other"
Error: 
You have an active prank. Broadcasting and pranks are not compatible. Disable one or the other`

**Using**:

`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.15;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "foundry-huff/HuffDeployer.sol";
import "../src/LilRouter.sol";

contract Deployer is Script {

    // serachers
    function setUp() public {

    }
    function run() public{
        address sandwich = HuffDeployer.broadcast("sando");
        console.log(address(sandwich));
    }
}`

`//forge script ./script/DeploySandwich.s.sol --rpc-url {} --broadcast --private-key {} `

Any ideas?

**Comment by mouseless-eth** [comment]
I still reccomend to use a create2 factory to deploy the raw bytecode (I.e [metamorphic](https://github.com/0age/metamorphic))
