### ISSUE TITLE
Optimize FrontRun [ENHANCEMENT]

### ISSUE THREAD

**Issue by praveenbm5** [mouseless-eth/rusty-sando#48]
The FrontRun Tx using Sando.huff in this repo consumes around 103k gas. 

And the state of the art bots use around 86k gas.  17% less. 

Ex. https://etherscan.io/tx/0xeeb288abdd22e1f2c26f3f46eef0ca769afb78910a248d3ae9de965f02cdb103

Link to the deployed contract and disassembled byte code used by them - https://library.dedaub.com/ethereum/address/0x6b75d8af000000e20b7a7ddf000ba900b4009a80/disassembled

How do we compare and port the optimizations used in this contrat into sando.huff? 

This issue is meant to host the discussion around the optimizations used by sando.huff and other searcher contracts.

**Comment by mouseless0x** [comment]
> The FrontRun Tx using Sando.huff in this repo consumes around 103k gas. 
> 
> And the state of the art bots use around 86k gas.  17% less. 
> 
> Ex. https://etherscan.io/tx/0xeeb288abdd22e1f2c26f3f46eef0ca769afb78910a248d3ae9de965f02cdb103
> 
> Link to the deployed contract and disassembled byte code used by them - https://library.dedaub.com/ethereum/address/0x6b75d8af000000e20b7a7ddf000ba900b4009a80/disassembled
> 
> How do we compare and port the optimizations used in this contrat into sando.huff? 
> 
> This issue is meant to host the discussion around the optimizations used by sando.huff and other searcher contracts.
> 

How are you measuring the gas used on the sando contract? Earlier this year it was very close to the top bots (couple tens to hundred gas off). Can you share the code used to test gasused? are you accounting for token dust/access list? 

The tx that u reference uses a token that isn't used in the tests... gas used is different per erc20 token...
