### ISSUE TITLE
what is the seppuku_astral_gate

### ISSUE THREAD

**Issue by cliff0412** [mouseless-eth/rusty-sando#6]
may i know what is seppuku_astral_gate?

**Comment by merklefruit** [comment]
it's just a jump label used to call the `seppuku` function which selfdestructs the contract

**Comment by cliff0412** [comment]
> 

thanks for your reply. but what is the helper contract

**Comment by ephz3nt** [comment]
searcher is real submit bundle tx to mev relay, so you need enough eth in searcher addree for pay gas;
helper like another address, it have seppuku(selfdestruct sandwich contract, carfuly), recover_eth and recover_weth permission, both can use the same address;
