### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'arithmetic operation overflow'

### ISSUE THREAD

**Issue by e7172** [mouseless-eth/rusty-sando#7]
Im having this error:
`thread 'tokio-runtime-worker' panicked at 'arithmetic operation overflow'`

Running:
`cargo run --bin rusty-sando --release`

We think is in **create_optimal_sandwich** func located in [/src/simulate/make_sandwich.rs](https://github.com/mouseless-eth/rusty-sando/tree/master/bot/src/simulate/make_sandwich.rs)

```
pub async fn create_optimal_sandwich(
    ingredients: &RawIngredients,
    sandwich_balance: U256,
    next_block: &BlockInfo,
    fork_factory: &mut ForkFactory,
    sandwich_maker: &SandwichMaker,
) -> Result<OptimalRecipe, SimulationError> {
    let optimal = juiced_quadratic_search(
        ingredients,
        U256::zero(),
        sandwich_balance,
        next_block,
        fork_factory,
    )
    .await?;

    #[cfg(test)]
    {
        println!("Optimal amount in: {}", optimal);
    }

    sanity_check(
        sandwich_balance,
        optimal,
        ingredients,
        next_block,
        sandwich_maker,
        fork_factory.new_sandbox_fork(),
    )
}
```

By running [/src/runner/mod.rs](https://github.com/mouseless-eth/rusty-sando/tree/master/bot/src/runner/mod.rs)

```
let mut optimal_sandwich = match make_sandwich::create_optimal_sandwich(
                        &raw_ingredients,
                        sandwich_balance,
                        &block_oracle.next_block,
                        &mut fork_factory,
                        &sandwich_maker,
                    )
                    .await
                    {
                        Ok(optimal) => optimal,
                        Err(e) => {
                            log::info!(
                                "{}",
                                format!("{:?} sim failed due to {:?}", &victim_hash, e).yellow()
                            );
                            return;
                        }
                    };

```

Any idea what may be causing this error?
Thanks!

**Comment by jamil-wittmann** [comment]
I have the same issue:
thread 'tokio-runtime-worker' panicked at 'arithmetic operation overflow', /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/primitive-types-0.12.1/src/lib.rs:38:1


were you able to figure this out?

**Comment by SadeRespector** [comment]
I get the same error, running Linux. Switched variables from mainnet to goerli. Also my rpc daemon returns an error about tracecallmany. Not sure if related. Went through the code and it seems the intervals variable array is what's the issue however I'm not familiar with rust and am still working this out. Will check back in if I figure it out.

**Comment by popfendi** [comment]
Did you fund the sandwich contract?

**Comment by SadeRespector** [comment]
> 

I did not, but I'll be sure to do that if it will help
